# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks  
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: make
        args: ["black"]
        language: system
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: make
        args: ["flake8"]
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: make
        args: ["mypy"]
        language: system
        pass_filenames: false
      - id: test
        name: test
        entry: make
        args: ["tests"]
        language: system
        pass_filenames: false