version: '3.8'

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    command: uvicorn app.server:app --host 0.0.0.0 --port 8020 --reload --workers 2
    volumes:
      - ./back/src/:/app/
    expose:
      - 8020  
    depends_on:
      - db      
    env_file:
      - ./db/.env.dev

  db:
    image: postgres:15.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./db/scripts:/docker-entrypoint-initdb.d
    env_file:
      - ./db/.env.dev
    ports:
      - 5432:5432

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    command: npm run dev.docker
    volumes:
      - ./front/src/:/front/src
    ports:
      - 5173  
      - 8021
    depends_on:
      - back     

  nginx:
      build: ./nginx
      ports:
        - 8015:8015
        - 8021:8021
      depends_on:
        - front

volumes:
  db_data: