version: '3.8'

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && uvicorn app.server:app --host 0.0.0.0 --port 8020 --reload --workers 2"
    volumes:
      - ./back/src/:/app/
    expose:
      - 8020  
    # ports:
    #   - 8020:8020
    depends_on:
      - db      
    env_file:
      - ./db/.env.dev
      - ./back/.env.dev
    restart: unless-stopped

  db:
    image: postgres:15.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./db/scripts:/docker-entrypoint-initdb.d
    env_file:
      - ./db/.env.dev
    ports:
      - 5432:5432
    restart: unless-stopped

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    command: npm run dev.docker
    volumes:
      - ./front/src/:/front/src
    ports:
      - 5173  
      - 8021      
    depends_on:
      - back    
    restart: unless-stopped 

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/static:/var/www/static
    ports:
      - 8015:8015
      - 8020:8020
      - 8021:8021
    depends_on:
      - front
    restart: unless-stopped

volumes:
  db_data: