"""database v1

Revision ID: 13adba72734f
Revises: 
Create Date: 2023-01-19 13:46:49.715038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13adba72734f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k_tip_vs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod_vs', sa.Integer(), nullable=False),
    sa.Column('modif', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nomer', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('priznak_vs', sa.Integer(), nullable=False),
    sa.Column('s_naznach_vs_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['k_tip_vs.id'], ),
    sa.ForeignKeyConstraint(['s_naznach_vs_id'], ['k_tip_vs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Типы  воздушных  судов.  Структура  классификатора'
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('s_aerodrom',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Готовность  аэродрома»'
    )
    op.create_table('s_deyatelnost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['s_deyatelnost.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Виды  деятельности  и  обеспечения  при  производстве  полетов»'
    )
    op.create_table('s_faktor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Группы  опасных  факторов»'
    )
    op.create_table('s_foiv',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Федеральные  органы  исполнительной  власти  (ФОИВ)»'
    )
    op.create_table('s_letnye_smeni',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Варианты  летных  смен»'
    )
    op.create_table('s_meteousloviya',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Варианты  метеоусловий»'
    )
    op.create_table('s_naznach_vs',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Назначение  ВС»'
    )
    op.create_table('s_oblachnost',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Виды  облачности»'
    )
    op.create_table('s_ogranich',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Причины  ограничений»'
    )
    op.create_table('s_operativ_uprav',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Формирования  оперативного  уровня  управления»'
    )
    op.create_table('s_osadki',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Виды  осадков»'
    )
    op.create_table('s_osveshennost',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Вариант  освещенности»'
    )
    op.create_table('s_period_ucheta',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Кодирование  периодов  учета»'
    )
    op.create_table('s_pogoda',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Соответствие  прогноза  погоды»'
    )
    op.create_table('s_posled',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Уровни  тяжести  последствий  событий»'
    )
    op.create_table('s_roda',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Рода  авиации»'
    )
    op.create_table('s_sobytiya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.Integer(), nullable=False),
    sa.Column('kod_posled', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Классификация  событий»'
    )
    op.create_table('s_strateg_uprav',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Формирования  оперативно-стратегического  уровня  управления»'
    )
    op.create_table('s_uprav',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Уровни  управления»'
    )
    op.create_table('s_vetrov_yavl',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Вид  ветровых  явлений»'
    )
    op.create_table('s_vidimost',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник  «Явления,  ухудшающие  видимость»'
    )
    op.create_table('structure_formations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_narusheniya_letnyh_smen',
    sa.Column('aerodrom', sa.Integer(), nullable=False),
    sa.Column('chast', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('massiv', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  базы  данных  «Нарушения  и  недостатки  при  проведении  летных  смен»'
    )
    op.create_table('t_plan_letnyh_smen',
    sa.Column('aerodrom', sa.Integer(), nullable=False),
    sa.Column('avia_sobit', sa.BOOLEAN(), nullable=False),
    sa.Column('chast', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod_meteo', sa.Integer(), nullable=False),
    sa.Column('kod_smeni', sa.Integer(), nullable=False),
    sa.Column('kod_vypoln', sa.Integer(), nullable=False),
    sa.Column('nalet', sa.DateTime(), nullable=False),
    sa.Column('nalet_den', sa.Integer(), nullable=False),
    sa.Column('nalet_dpmu', sa.DateTime(), nullable=False),
    sa.Column('nalet_dsmu', sa.DateTime(), nullable=False),
    sa.Column('nalet_ncmu', sa.DateTime(), nullable=False),
    sa.Column('nalet_noch', sa.Integer(), nullable=False),
    sa.Column('nalet_npmu', sa.DateTime(), nullable=False),
    sa.Column('podrazd', sa.String(length=8), nullable=False),
    sa.Column('polet', sa.Integer(), nullable=False),
    sa.Column('polet_den', sa.Integer(), nullable=False),
    sa.Column('polet_noch', sa.Integer(), nullable=False),
    sa.Column('prognoz', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  базы  данных  «Планирование  и  выполнение  летных  смен»'
    )
    op.create_table('t_vs_chasti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.Integer(), nullable=False),
    sa.Column('shtat', sa.Integer(), nullable=False),
    sa.Column('spisok', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Связанная  таблица  «Воздушные  суда  части»'
    )
    op.create_table('k_aerodrom',
    sa.Column('dolgota', sa.String(length=255), nullable=False),
    sa.Column('foiv', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_aero', sa.String(length=255), nullable=False),
    sa.Column('index_mezhd', sa.String(length=255), nullable=False),
    sa.Column('index_ros', sa.String(length=255), nullable=False),
    sa.Column('index_voen', sa.Integer(), nullable=True),
    sa.Column('klas_grazhd', sa.String(length=1), nullable=True),
    sa.Column('klas_voen', sa.Integer(), nullable=True),
    sa.Column('kod_ogran', sa.Integer(), nullable=False),
    sa.Column('kod_okrug', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('s_strateg_uprav_1_id', sa.Integer(), nullable=False),
    sa.Column('s_strateg_uprav_2_id', sa.Integer(), nullable=False),
    sa.Column('shirota', sa.String(length=255), nullable=False),
    sa.Column('sovmets_isp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kod_ogran'], ['s_ogranich.id'], ),
    sa.ForeignKeyConstraint(['s_strateg_uprav_1_id'], ['s_strateg_uprav.id'], ),
    sa.ForeignKeyConstraint(['s_strateg_uprav_2_id'], ['s_strateg_uprav.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Классификатор  «Аэродромы  базирования»'
    )
    op.create_table('k_podgr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('s_faktor_id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['s_faktor_id'], ['s_faktor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Классификатор  «Подгруппы  причин»'
    )
    op.create_table('s_itog_vs_tip',
    sa.Column('god', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod_strukt', sa.Integer(), nullable=False),
    sa.Column('kod_vs', sa.Integer(), nullable=False),
    sa.Column('nalet', sa.DateTime(), nullable=False),
    sa.Column('nalet_den', sa.Integer(), nullable=False),
    sa.Column('nalet_dpmu', sa.DateTime(), nullable=False),
    sa.Column('nalet_dsmu', sa.DateTime(), nullable=False),
    sa.Column('nalet_ncmu', sa.DateTime(), nullable=False),
    sa.Column('nalet_noch', sa.Integer(), nullable=False),
    sa.Column('nalet_npmu', sa.DateTime(), nullable=False),
    sa.Column('period', sa.String(length=255), nullable=False),
    sa.Column('polet', sa.Integer(), nullable=False),
    sa.Column('polet_den', sa.Integer(), nullable=False),
    sa.Column('polet_noch', sa.Integer(), nullable=False),
    sa.Column('s_period_ucheta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['s_period_ucheta_id'], ['s_period_ucheta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  базы  данных  данных  «Итоги  летной  деятельности,  за  периоды  времени  по  типам  ВС»'
    )
    op.create_table('t_bezopasnost',
    sa.Column('god', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod_strukt', sa.Integer(), nullable=False),
    sa.Column('massiv', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=255), nullable=False),
    sa.Column('s_period_ucheta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['s_period_ucheta_id'], ['s_period_ucheta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  базы  данных  «Показатели  безопасности  полетов  за  период  времени»'
    )
    op.create_table('t_ispravnost_vs',
    sa.Column('arz', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('gotov', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ispr', sa.Integer(), nullable=False),
    sa.Column('kod_strukt', sa.Integer(), nullable=False),
    sa.Column('kod_vs', sa.Integer(), nullable=False),
    sa.Column('reglam', sa.Integer(), nullable=False),
    sa.Column('shtat', sa.Integer(), nullable=False),
    sa.Column('t_vs_chasti_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['t_vs_chasti_id'], ['t_vs_chasti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  базы  данных  «Состояние  исправности  ВС»'
    )
    op.create_table('t_itog_vs',
    sa.Column('dosroch', sa.Integer(), nullable=False),
    sa.Column('god', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod_strukt', sa.Integer(), nullable=False),
    sa.Column('kol_den', sa.Integer(), nullable=False),
    sa.Column('kol_noch', sa.Integer(), nullable=False),
    sa.Column('kol_prognoz', sa.Integer(), nullable=False),
    sa.Column('kol_smesh', sa.Integer(), nullable=False),
    sa.Column('nalet', sa.DateTime(), nullable=False),
    sa.Column('nalet_den', sa.Integer(), nullable=False),
    sa.Column('nalet_dpmu', sa.DateTime(), nullable=False),
    sa.Column('nalet_dsmu', sa.DateTime(), nullable=False),
    sa.Column('nalet_ncmu', sa.DateTime(), nullable=False),
    sa.Column('nalet_noch', sa.Integer(), nullable=False),
    sa.Column('nalet_npmu', sa.DateTime(), nullable=False),
    sa.Column('period', sa.String(length=255), nullable=False),
    sa.Column('polet', sa.Integer(), nullable=False),
    sa.Column('polet_den', sa.Integer(), nullable=False),
    sa.Column('polet_noch', sa.Integer(), nullable=False),
    sa.Column('procent_prognoz', sa.Integer(), nullable=False),
    sa.Column('s_period_ucheta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['s_period_ucheta_id'], ['s_period_ucheta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  базы  данных  «Итоги  летной  деятельности,  за  периоды  времени  по  всем  типам  ВС»'
    )
    op.create_table('t_nalet_vs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod_vs', sa.Integer(), nullable=False),
    sa.Column('nalet', sa.DateTime(), nullable=False),
    sa.Column('nalet_den', sa.Integer(), nullable=False),
    sa.Column('nalet_dpmu', sa.DateTime(), nullable=False),
    sa.Column('nalet_dsmu', sa.DateTime(), nullable=False),
    sa.Column('nalet_ncmu', sa.DateTime(), nullable=False),
    sa.Column('nalet_noch', sa.Integer(), nullable=False),
    sa.Column('nalet_npmu', sa.DateTime(), nullable=False),
    sa.Column('polet', sa.Integer(), nullable=False),
    sa.Column('polet_den', sa.Integer(), nullable=False),
    sa.Column('polet_noch', sa.Integer(), nullable=False),
    sa.Column('t_plan_letnyh_smen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['t_plan_letnyh_smen_id'], ['t_plan_letnyh_smen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  базы  данных  данных  «Учет  налета  ВС  и  экипаже  по  типам  ВС»'
    )
    op.create_table('t_nedostatki',
    sa.Column('god', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('massiv', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=255), nullable=False),
    sa.Column('s_period_ucheta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['s_period_ucheta_id'], ['s_period_ucheta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  базы  данных  данных  «Количество  нарушений  и  недостатков  по  периодам  времени»'
    )
    op.create_table('t_poteri',
    sa.Column('god', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod_strukt', sa.Integer(), nullable=False),
    sa.Column('massiv', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=255), nullable=False),
    sa.Column('s_period_ucheta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['s_period_ucheta_id'], ['s_period_ucheta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  базы  данных  «Потери  в  результате  авиационных  событий,  за  периоды  времени»'
    )
    op.create_table('t_poteri_vs',
    sa.Column('god', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod_strukt', sa.Integer(), nullable=False),
    sa.Column('kod_vs', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=255), nullable=False),
    sa.Column('poter', sa.Integer(), nullable=False),
    sa.Column('pov', sa.Integer(), nullable=False),
    sa.Column('s_period_ucheta_id', sa.Integer(), nullable=False),
    sa.Column('ser_pov', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['s_period_ucheta_id'], ['s_period_ucheta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  базы  данных  «Потери  ВС  по  типам  по  периодам  времени»'
    )
    op.create_table('t_uchet_sobytij',
    sa.Column('god', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod_strukt', sa.Integer(), nullable=False),
    sa.Column('massiv', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=255), nullable=False),
    sa.Column('s_period_ucheta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['s_period_ucheta_id'], ['s_period_ucheta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  базы  данных  «Учет  авиационных  событий  по  подгруппам  факторов,  за  периоды  времени»'
    )
    op.create_table('t_uroven_ls',
    sa.Column('god', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod_strukt', sa.Integer(), nullable=False),
    sa.Column('kod_vs', sa.Integer(), nullable=False),
    sa.Column('massiv', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=255), nullable=False),
    sa.Column('s_period_ucheta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['s_period_ucheta_id'], ['s_period_ucheta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  базы  данных  «Квалификация  и  уровень  подготовки  летного  состава  (летчики)»'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('fio', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('k_prichiny',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k_podgr_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['k_podgr_id'], ['k_podgr.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Классификатор  «Причины  событий»'
    )
    op.create_table('t_aerodrom',
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k_aerodrom_id', sa.Integer(), nullable=False),
    sa.Column('konesh', sa.Time(), nullable=False),
    sa.Column('nash', sa.Time(), nullable=False),
    sa.Column('s_aerodrom_id', sa.Integer(), nullable=False),
    sa.Column('s_ogranich_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['k_aerodrom_id'], ['k_aerodrom.id'], ),
    sa.ForeignKeyConstraint(['s_aerodrom_id'], ['s_aerodrom.id'], ),
    sa.ForeignKeyConstraint(['s_ogranich_id'], ['s_ogranich.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  базы  данных  «Готовность  аэродромов»'
    )
    op.create_table('t_meteo',
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('davlenie', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k_aerodrom_id', sa.Integer(), nullable=False),
    sa.Column('napr_vetra', sa.Integer(), nullable=False),
    sa.Column('ngo', sa.Integer(), nullable=False),
    sa.Column('oblachnost', sa.Integer(), nullable=False),
    sa.Column('osadki', sa.Integer(), nullable=False),
    sa.Column('s_oblachnost_id', sa.Integer(), nullable=False),
    sa.Column('s_osadki_id', sa.Integer(), nullable=False),
    sa.Column('s_vetrov_yavl_id', sa.Integer(), nullable=False),
    sa.Column('s_vidimost_id', sa.Integer(), nullable=False),
    sa.Column('skorost_vetra_max', sa.Integer(), nullable=False),
    sa.Column('skorost_vetra_min', sa.Integer(), nullable=False),
    sa.Column('temp_max', sa.Integer(), nullable=False),
    sa.Column('temp_min', sa.Integer(), nullable=False),
    sa.Column('vgo', sa.Integer(), nullable=False),
    sa.Column('vid_gor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vid_vert', sa.Integer(), nullable=False),
    sa.Column('vlazhnost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['k_aerodrom_id'], ['k_aerodrom.id'], ),
    sa.ForeignKeyConstraint(['s_oblachnost_id'], ['s_oblachnost.id'], ),
    sa.ForeignKeyConstraint(['s_osadki_id'], ['s_osadki.id'], ),
    sa.ForeignKeyConstraint(['s_vetrov_yavl_id'], ['s_vetrov_yavl.id'], ),
    sa.ForeignKeyConstraint(['s_vidimost_id'], ['s_vidimost.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  «Прогноз  метеообстановки  на  аэродроме»'
    )
    op.create_table('t_org_struct',
    sa.Column('chast', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_chasti', sa.Integer(), nullable=False),
    sa.Column('k_aerodrom_id', sa.Integer(), nullable=True),
    sa.Column('kod_okrug', sa.Integer(), nullable=True),
    sa.Column('mesto', sa.String(length=255), nullable=True),
    sa.Column('ospd_adr', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('poch_adr', sa.String(length=255), nullable=True),
    sa.Column('poch_index', sa.String(length=255), nullable=True),
    sa.Column('s_uprav_id', sa.Integer(), nullable=False),
    sa.Column('usl_vch', sa.String(length=255), nullable=False),
    sa.Column('vch', sa.String(length=255), nullable=True),
    sa.Column('vch_name', sa.String(length=255), nullable=True),
    sa.Column('vch_short_name', sa.String(length=255), nullable=True),
    sa.Column('zspd_adr', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['k_aerodrom_id'], ['k_aerodrom.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['t_org_struct.id'], ),
    sa.ForeignKeyConstraint(['s_uprav_id'], ['s_uprav.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  «Организационная  структура  авиационной  системы»'
    )
    op.create_table('t_uchet_posled',
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('dop_identif', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k_podgr_id', sa.Integer(), nullable=False),
    sa.Column('k_prichiny_id', sa.Integer(), nullable=False),
    sa.Column('kod_prich', sa.Integer(), nullable=False),
    sa.Column('kod_strukt', sa.Integer(), nullable=False),
    sa.Column('pog_ekipazh', sa.Integer(), nullable=False),
    sa.Column('pog_pass', sa.Integer(), nullable=False),
    sa.Column('pog_zem', sa.Integer(), nullable=False),
    sa.Column('pos_ekipazh', sa.Integer(), nullable=False),
    sa.Column('pos_pass', sa.Integer(), nullable=False),
    sa.Column('pos_zem', sa.Integer(), nullable=False),
    sa.Column('poter', sa.Integer(), nullable=False),
    sa.Column('pov', sa.Integer(), nullable=False),
    sa.Column('ser_pov', sa.Integer(), nullable=False),
    sa.Column('ushcherb', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['k_podgr_id'], ['k_podgr.id'], ),
    sa.ForeignKeyConstraint(['k_prichiny_id'], ['k_prichiny.id'], name='fr_t_uchet_posled_k_prichiny_id'),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  базы  данных  «Оперативный  учет  авиационных  событий  и  их  последствий»'
    )
    op.create_table('t_uchet_poter_vs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod_vs', sa.Integer(), nullable=False),
    sa.Column('poter', sa.Integer(), nullable=False),
    sa.Column('pov', sa.Integer(), nullable=False),
    sa.Column('ser_pov', sa.Integer(), nullable=False),
    sa.Column('t_uchet_posled_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['t_uchet_posled_id'], ['t_uchet_posled.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица  базы  данных  данных  «Оперативный  учет  потерь  и  повреждений  ВС  по  типам»'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_uchet_poter_vs')
    op.drop_table('t_uchet_posled')
    op.drop_table('t_org_struct')
    op.drop_table('t_meteo')
    op.drop_table('t_aerodrom')
    op.drop_table('k_prichiny')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('t_uroven_ls')
    op.drop_table('t_uchet_sobytij')
    op.drop_table('t_poteri_vs')
    op.drop_table('t_poteri')
    op.drop_table('t_nedostatki')
    op.drop_table('t_nalet_vs')
    op.drop_table('t_itog_vs')
    op.drop_table('t_ispravnost_vs')
    op.drop_table('t_bezopasnost')
    op.drop_table('s_itog_vs_tip')
    op.drop_table('k_podgr')
    op.drop_table('k_aerodrom')
    op.drop_table('t_vs_chasti')
    op.drop_table('t_plan_letnyh_smen')
    op.drop_table('t_narusheniya_letnyh_smen')
    op.drop_table('structure_formations')
    op.drop_table('s_vidimost')
    op.drop_table('s_vetrov_yavl')
    op.drop_table('s_uprav')
    op.drop_table('s_strateg_uprav')
    op.drop_table('s_sobytiya')
    op.drop_table('s_roda')
    op.drop_table('s_posled')
    op.drop_table('s_pogoda')
    op.drop_table('s_period_ucheta')
    op.drop_table('s_osveshennost')
    op.drop_table('s_osadki')
    op.drop_table('s_operativ_uprav')
    op.drop_table('s_ogranich')
    op.drop_table('s_oblachnost')
    op.drop_table('s_naznach_vs')
    op.drop_table('s_meteousloviya')
    op.drop_table('s_letnye_smeni')
    op.drop_table('s_foiv')
    op.drop_table('s_faktor')
    op.drop_table('s_deyatelnost')
    op.drop_table('s_aerodrom')
    op.drop_table('roles')
    op.drop_table('k_tip_vs')
    # ### end Alembic commands ###
