"""user role

Revision ID: 7363a5cde5e9
Revises: d1c896b82e45
Create Date: 2023-01-09 11:36:07.905097

"""
from alembic import op
import sqlalchemy as sa
from app.db.models import roles_table


# revision identifiers, used by Alembic.
revision = '7363a5cde5e9'
down_revision = 'd1c896b82e45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###

    op.bulk_insert(roles_table,
        [
            {'name':'Гость'},
            {'name':'Оператор'},
            {'name':'Функционер'},
            {'name':'Администратор'},
        ]
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
