"""database_v1

Revision ID: 8c598f6afa40
Revises: 7363a5cde5e9
Create Date: 2023-01-09 16:31:33.745718

"""
from alembic import op
import sqlalchemy as sa
from app.db.models import s_sobytiya_table, s_posled_table

# revision identifiers, used by Alembic.
revision = '8c598f6afa40'
down_revision = '7363a5cde5e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k_aerodrom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Классификатор "Аэродромы базирования"'
    )
    op.create_table('k_prichiny',
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('k_podgr_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('k_podgr_id', 'id'),
    comment='Классификатор "Причины событий"'
    )
    op.create_table('k_tip_vs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Типы воздушных судов. Структура классификатора'
    )
    op.create_table('s_aerodrom',
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Готовность аэродрома"'
    )
    op.create_table('s_deyatelnost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['s_deyatelnost.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Виды деятельности и обеспечения при производстве полетов"'
    )
    op.create_table('s_faktor',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Группы опасных факторов"'
    )
    op.create_table('s_foiv',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Федеральные органы исполнительной власти (ФОИВ)"'
    )
    op.create_table('s_itog_vs_tip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица базы данных данных "Итоги летной деятельности, за периоды времени по типам ВС"'
    )
    op.create_table('s_letnye_smeni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Варианты летных смен"'
    )
    op.create_table('s_meteousloviya',
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Варианты метеоусловий"'
    )
    op.create_table('s_naznach_vs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Назначение ВС"'
    )
    op.create_table('s_oblachnost',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Виды облачности"'
    )
    op.create_table('s_ogranich',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Причины ограничений"'
    )
    op.create_table('s_operativ_uprav',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Формирования оперативного уровня управления"'
    )
    op.create_table('s_osadki',
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Виды осадков"'
    )
    op.create_table('s_osveshennost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Вариант освещенности"'
    )
    op.create_table('s_period_ucheta',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Кодирование периодов учета"'
    )
    op.create_table('s_pogoda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Соответствие прогноза погоды"'
    )
    op.create_table('s_posled',
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Уровни тяжести последствий событий"'
    )
    op.create_table('s_roda',
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Рода авиации"'
    )
    op.create_table('s_sobytiya',
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('code_posled', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Классификация событий"'
    )
    op.create_table('s_strateg_uprav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Формирования оперативно-стратегического уровня управления"'
    )
    op.create_table('s_uprav',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Уровни управления"'
    )
    op.create_table('s_vetrov_yavl',
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Вид ветровых явлений"'
    )
    op.create_table('s_vidimost',
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник "Явления, ухудшающие видимость"'
    )
    op.create_table('t_aerodrom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица базы данных "Готовность аэродромов"'
    )
    op.create_table('t_bezopasnost',
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица базы данных "Показатели безопасности полетов за период времени"'
    )
    op.create_table('t_ispravnost_vs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица базы данных "Состояние исправности ВС"'
    )
    op.create_table('t_itog_vs',
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица базы данных "Итоги летной деятельности, за периоды времени по всем типам ВС"'
    )
    op.create_table('t_meteo',
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Прогноз метеообстановки на аэродроме"'
    )
    op.create_table('t_nalet_vs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    comment='Таблица базы данных данных "Учет налета ВС и экипаже по типам ВС"'
    )
    op.create_table('t_narusheniya_letnyh_smen',
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица базы данных "Нарушения и недостатки при проведении летных смен"'
    )
    op.create_table('t_nedostatki',
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица базы данных данных "Количество нарушений и недостатков по периодам времени"'
    )
    op.create_table('t_org_struct',
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица "Организационная структура авиационной системы"'
    )
    op.create_table('t_plan_letnyh_smen',
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица базы данных "Планирование и выполнение летных смен"'
    )
    op.create_table('t_poteri',
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица базы данных "Потери в результате авиационных событий, за периоды времени"'
    )
    op.create_table('t_poteri_vs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица базы данных "Потери ВС по типам по периодам времени"'
    )
    op.create_table('t_uchet_posled',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица базы данных "Оперативный учет авиационных событий и их последствий"'
    )
    op.create_table('t_uchet_poter_vs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица базы данных данных "Оперативный учет потерь и повреждений ВС по типам"'
    )
    op.create_table('t_uchet_sobytij',
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица базы данных "Учет авиационных событий по подгруппам факторов, за периоды времени"'
    )
    op.create_table('t_uroven_ls',
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица базы данных "Квалификация и уровень подготовки летного состава (летчики)"'
    )
    op.create_table('t_vs_chasti',
    sa.Column('prim', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Связанная таблица "Воздушные суда части"'
    )
    op.create_table('k_podgr',
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_faktor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['s_faktor_id'], ['s_faktor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Классификатор "Подгруппы причин"'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('k_podgr')
    op.drop_table('t_vs_chasti')
    op.drop_table('t_uroven_ls')
    op.drop_table('t_uchet_sobytij')
    op.drop_table('t_uchet_poter_vs')
    op.drop_table('t_uchet_posled')
    op.drop_table('t_poteri_vs')
    op.drop_table('t_poteri')
    op.drop_table('t_plan_letnyh_smen')
    op.drop_table('t_org_struct')
    op.drop_table('t_nedostatki')
    op.drop_table('t_narusheniya_letnyh_smen')
    op.drop_table('t_nalet_vs')
    op.drop_table('t_meteo')
    op.drop_table('t_itog_vs')
    op.drop_table('t_ispravnost_vs')
    op.drop_table('t_bezopasnost')
    op.drop_table('t_aerodrom')
    op.drop_table('s_vidimost')
    op.drop_table('s_vetrov_yavl')
    op.drop_table('s_uprav')
    op.drop_table('s_strateg_uprav')
    op.drop_table('s_sobytiya')
    op.drop_table('s_roda')
    op.drop_table('s_posled')
    op.drop_table('s_pogoda')
    op.drop_table('s_period_ucheta')
    op.drop_table('s_osveshennost')
    op.drop_table('s_osadki')
    op.drop_table('s_operativ_uprav')
    op.drop_table('s_ogranich')
    op.drop_table('s_oblachnost')
    op.drop_table('s_naznach_vs')
    op.drop_table('s_meteousloviya')
    op.drop_table('s_letnye_smeni')
    op.drop_table('s_itog_vs_tip')
    op.drop_table('s_foiv')
    op.drop_table('s_faktor')
    op.drop_table('s_deyatelnost')
    op.drop_table('s_aerodrom')
    op.drop_table('k_tip_vs')
    op.drop_table('k_prichiny')
    op.drop_table('k_aerodrom')
    # ### end Alembic commands ###
