"""user login

Revision ID: d1c896b82e45
Revises: f5e0d6053aac
Create Date: 2023-01-09 09:44:40.059501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1c896b82e45'
down_revision = 'f5e0d6053aac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('DELETE FROM users')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('fio', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=256), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###

    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password')
    op.drop_column('users', 'fio')
    op.drop_column('users', 'username')
    op.drop_column('users', 'email')
    
    # ### end Alembic commands ###
