"""structure_formations

Revision ID: f5e0d6053aac
Revises: 45a47e5af6f2
Create Date: 2022-12-14 05:22:12.018070


"""
from alembic import op
import sqlalchemy as sa
from app.db.models import structure_formations_table


# revision identifiers, used by Alembic.
revision = 'f5e0d6053aac'
down_revision = '45a47e5af6f2'
branch_labels = None
depends_on = None

def insert_structure_formations(name: str, pid: int = None) -> int:
    conn = op.get_bind()
    query = structure_formations_table.insert().values(name=name, pid=pid).returning(structure_formations_table.c.id)
    res = conn.execute(query).fetchall()
    return res[0][0]    

def insert_data():
    root_id = insert_structure_formations('Авиация ВС РФ')
    op.bulk_insert(structure_formations_table,
        [
            {'name':'ВМФ', 'pid': root_id},
            {'name':'ВКС', 'pid': root_id},            
            {'name':'РОСТО', 'pid': root_id},
        ]
    )

    id = insert_structure_formations('ОСК ЗВО', root_id)
    id = insert_structure_formations('6 А ВВС и ПВО', id)

    op.bulk_insert(structure_formations_table,
        [
            {'name':'NNN сад', 'pid': id},
            {'name':'NN браа', 'pid': id},            
            {'name':'NN отсап', 'pid': id},
            {'name':'NN овн', 'pid': id},
        ]
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structure_formations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    insert_data()



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('structure_formations')
    # ### end Alembic commands ###
